---
# tasks file for common
- name: set timezone
  community.general.timezone:
    hwclock: "UTC"
    name: "{{ common_timezone }}"

- name: install packages
  ansible.builtin.apt:
    cache_valid_time: 86400
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - git-secrets
    - gpg
    - jq
    - make
    - python3
    - python3-pip

- name: install python modules
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  with_items:
    - yq
